default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :lint do
      gradle(task: "lint")
  end

  lane :test do
    gradle(task: "test lint --stacktrace")
  end

  desc "Runs build"
  lane :build_release do
    gradle(
        task: "bundle",
        build_type: "Release"
    )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean bundleRelease")
    upload_to_play_store()
  end
end
