name: Android CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  keyAlias: ${{ secrets.KEY_ALIAS }}
  keyBase64: ${{ secrets.KEYSTORE }}
  keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
  keyPassword: ${{ secrets.KEY_PASSWORD }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is running on a ${{ runner.os }} server hosted by GitHub!"
      - uses: actions/checkout@v5
      - name: set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      #      - name: Create service_account.json
      #        run: |
      #          cat /home/runner/work/MyDailyPet/MyDailyPet/app/google-services.json | base64
      #          echo $GOOGLE_SERVICES_DATA > /home/runner/work/MyDailyPet/MyDailyPet/app/google-services.json
      - name: Config enviroment
        #        env:
        #          AD_MOB_ID: ${{ secrets.AD_MOB_ID }}
        #          BANNER_AD_MOB_ID: ${{ secrets.BANNER_AD_MOB_ID }}
        #          GOOGLE_SERVICES_DATA: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        run: |
          chmod +x ./.github/workflows/scripts.sh
          ./.github/workflows/scripts.sh
        shell: bash
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembleDebug --stacktrace
      - name: Unit tests
        run: ./gradlew test
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
      - run: echo "Generating apk"
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17
      #- name: Create service_account.json
          #        run: |
          #          cat /home/runner/work/MyDailyPet/MyDailyPet/app/google-services.json | base64
          #          echo $GOOGLE_SERVICES_DATA > /home/runner/work/MyDailyPet/MyDailyPet/app/google-services.json
      - name: Config enviroment
          #        env:
          #          AD_MOB_ID: ${{ secrets.AD_MOB_ID }}
          #          BANNER_AD_MOB_ID: ${{ secrets.BANNER_AD_MOB_ID }}
          #          GOOGLE_SERVICES_DATA: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        run: |
            chmod +x ./.github/workflows/scripts.sh
            ./.github/workflows/scripts.sh
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build APK
        run: |
          ./gradlew assembleRelease --stacktrace
        env:
          KEY_STORE_PASSWORD: $keyStorePassword
          KEY_PASSWORD: $keyPassword
      - name: Build AAB
        run: |
          ./gradlew app:bundleRelease --stacktrace
        env:
          KEY_STORE_PASSWORD: $keyStorePassword
          KEY_PASSWORD: $keyPassword
      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: Release aab
          path: |
            app/build/outputs/bundle/release/app-release.aab
            app/build/outputs/apk/release/app-release.apk
    needs: test
