name: Android CI

on:
  push:
    branches: [ "develop","main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "This job is running on a ${{ runner.os }} server hosted by GitHub!"
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
      env:
        run: 
          echo AD_MOB_ID="{{secrets.AD_MOB_ID}}" > ./local.properties
          echo BANNER_AD_MOB_ID="{{secrets.BANNER_AD_MOB_ID}}" > ./local.properties
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
