name: Android CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  AD_MOB_ID: ${{ secrets.AD_MOB_ID }}
  BANNER_AD_MOB_ID: ${{ secrets.BANNER_AD_MOB_ID }}
  GOOGLE_SERVICES_DATA: ${{ secrets.SERVICE_ACCOUNT_JSON }}
  KEYSTORE: ${{ secrets.KEYSTORE }}
  KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
  KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

jobs:
  test:
    name: Unit tests & Lint
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is running on a ${{ runner.os }} server hosted by GitHub!"
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - &BuildEnv
        name: Config enviroment
        run: |
          chmod +x ./.github/workflows/scripts.sh
          ./.github/workflows/scripts.sh
          chmod +x gradlew
        shell: bash
      - name: Unit tests
        run: ./gradlew test lint --stacktrace
  build:
    name: Generate Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17
          cache: gradle
      - *BuildEnv
      - name: Android Build
        run: |
          ./gradlew assembleRelease app:bundleRelease --parallel --build-cache --stacktrace
        env:
          KEY_STORE_PASSWORD: $KEY_STORE_PASSWORD
          KEY_PASSWORD: $KEY_PASSWORD
      - name: Upload artifacts from release (aab e apk)
        uses: actions/upload-artifact@v4
        with:
          name: Release apk e aab-${{ github.ref_name }}
          path: |
            app/build/outputs/bundle/release/app-release.aab
            app/build/outputs/apk/release/app-release.apk
    needs: test
