name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome ${{ github.actor }}, thank you for send your first issue"
        pr-message: "Welcome ${{ github.actor }}, thank you for send your first pull request"
